spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/kitchen_saver
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=kitchensaver_secret_key
jwt.expiration=864000000
spring.main.allow-bean-definition-overriding=true
file.upload-dir=/tmp/uploads/
spring.resources.static-locations=file:${file.upload-dir}

